### ISSUE TITLE
Resolve blockers to updating to HAPI FHIR 6.4.1 and later

### ISSUE THREAD

**Issue by jack-h-wang** [CDCgov/prime-reportstream#16913]
### User Story
As an RS engineer, I want to remain on current and supported versions of dependencies.

### Description/Use Case
It appears a breaking change was introduced in HAPI (Core) 6.4.1 or later (ca.uhn.hapi.fhir:org.hl7.fhir.r4). We need to resolve any blockers that prevent us from updating to the latest version. UPDATE: As noted in the comments bellow, the HAPI FHIR libraries are currently incompatible with HAPI Core 6.4.1+. Thus the HAPI Core libraries should not be pinned so that gradle can resolve the recommended version.

### Dev Notes
Check out the following PRs (or their successors if they have been superceded) and note an error when attempting to build:
- #16911

```
> Task :prime-router:compileKotlin
e: file:///home/runner/work/prime-reportstream/prime-reportstream/prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/ConstantResolver.kt:146:1 Class 'FhirPathCustomResolver' is not abstract and does not implement abstract member public abstract fun paramIsType(p0: String!, p1: Int): Boolean defined in org.hl7.fhir.r4.fhirpath.FHIRPathEngine.IEvaluationContext
```

- #16912 (This error can probably be resolved if we re-run it. There is another ticket to look into this error specifically.)

```
Run ./.github/actions/vpn-azure
Run azure/login@v2
Error: Login failed with Error: Not all parameters are provided in 'creds'. Double-check if all keys are defined in 'creds': 'clientId', 'clientSecret', 'tenantId'.. Double check if the 'auth-type' is correct. Refer to https://github.com/Azure/login#readme for more information.
```

### Acceptance Criteria
- [ ] Update to HAPI libraries to latest versions without any test failures

**Comment by JFisk42** [comment]
Some notes from what I've found while digging into this:

The root error `Class 'FhirPathCustomResolver' is not abstract and does not implement abstract member public abstract fun paramIsType` is easily solvable. When fixed a new error reveals itself: `AbstractMethod Receiver class org.hl7.fhir.r4.hapi.ctx.HapiWorkerContext does not define or inherit an implementation of the resolved method 'abstract java.util.List fetchResourcesByType(java.lang.Class)' of interface org.hl7.fhir.r4.context.IWorkerContext.`. 

This cannot be resolved because HAPI has not yet implemented the fix internally. This state is only acheivable when attempting to use HAPI library versions which go against their recommended versions (ie pinning this library version instead of allowing it to be resolved by gradle).

What is going on here is that there are several sets of related HAPI libraries. From our gradle file:
```
implementation("ca.uhn.hapi.fhir:hapi-fhir-structures-r4:7.4.5")
implementation("ca.uhn.hapi.fhir:hapi-fhir-caching-caffeine:7.4.5")
implementation("ca.uhn.hapi.fhir:hapi-fhir-client:7.4.5")

implementation("ca.uhn.hapi.fhir:org.hl7.fhir.utilities:6.4.0")
implementation("ca.uhn.hapi.fhir:org.hl7.fhir.r4:6.4.0")

implementation("ca.uhn.hapi:hapi-base:2.5.1")
implementation("ca.uhn.hapi:hapi-structures-v251:2.5.1")
implementation("ca.uhn.hapi:hapi-structures-v27:2.5.1")
```
The first three are the "HAPI FHIR" libraries. The next two are "HAPI Core" and the last few are HL7 related. The HAPI Core library introduced a change to IWorkerContext in 6.4.1 and as of this week HAPI FHIR has not been updated to work with HAPI Core 6.4.1+. 

Again, this is only an issue because we have the HAPI Core libraries pinned instead of allowing gradle to resolve them through HAPI FHIR. This is obviously not supported and HAPI FHIR's lead engineer confirmed this is incorrect use: https://github.com/hapifhir/hapi-fhir/issues/6572.

**Comment by JFisk42** [comment]
⚠️ Additional issue found:

I wanted to update all our HAPI libraries as dependabot has been having issues with them. When attempting to update the HAPI FHIR libraries to 7.6.1, the following error occurs:
```
> Task :prime-router:compileKotlin

[740](https://github.com/CDCgov/prime-reportstream/actions/runs/13223844102/job/36912174428?pr=16879#step:4:752)e: warnings found and -Werror specified

[741](https://github.com/CDCgov/prime-reportstream/actions/runs/13223844102/job/36912174428?pr=16879#step:4:753)w: file:///home/runner/work/prime-reportstream/prime-reportstream/prime-router/src/main/kotlin/transport/GAENTransport.kt:219:41 'static fun randomAlphanumeric(p0: Int): String!' is deprecated. Deprecated in Java.
```

This method is deprecated and can easily be adjusted to using a similar non-deprecated method. https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/RandomStringUtils.html#randomAlphanumeric(int)
